### ISSUE TITLE
Installation issue on Windows

### ISSUE THREAD

**Issue by cjmiska** [ronik-design/slush-gh-pages#1]
I'm getting the following error when trying to install:

`Failed at the fsevents@1.0.14 install script: node-pre-gyp install --fallback-to-build`

I'm using node 6.6 and npm 3.10.2.

As I understand it, fsevents is an OSX specific package, does that mean slush-gh-pages isn't supported on Windows?

**Comment by mshick** [comment]
I would like for it to work on windows, so let me investigate.

Generally fsevents is required for watch tasks, but should install the
drivers as an optional dependency, so it shouldn't cause problems.

Until I have a chance to really look at it, could you perhaps try
installing it without the shrinkwrap? So 'npm install slush-gh-pages -g
--no-shrinkwrap' and see if maybe that's the problem?

**Comment by cjmiska** [comment]
Yep, that worked.

**Comment by mshick** [comment]
Ah, okay good. There must be things about the shrink wrap I don't
understand... Will investigate and update. Thanks for testing it!

**Comment by mshick** [comment]
@cjmiska I removed the shrinkwrap and published. Hopefully it will all work normally for you on Windows. Will spend more time figuring out the proper way to shrinkwrap.
